config/routes.rb
Rails.application.routes.draw do
  root 'lists#roulette'
  post 'remove_from_queue' => 'lists#remove_from_queue'
  post 'remove_from_list' => 'lists#remove_from_list'
  get 'new_list' => 'lists#new'
  get 'lists' => 'lists#all'
  get 'view_list' => 'lists#show'
  get 'edit_list' => 'lists#edit'
  get 'search' => 'movies#search'
  get 'search_results' => 'movies#search_results'
  get 'details/:id' => 'movies#details'
  get 'details' => 'movies#details'
  get 'save' => 'lists#save'
  get 'test' => 'movies#test'
  get 'roulette' => 'lists#roulette'
  get 'queue' => 'lists#queue'
  get 'filter' => 'lists#filter'
  get 'spin' => 'lists#spin'
  post 'add' => 'lists#add'
  post 'queue' => 'lists#add_to_queue'
  devise_for :users
  resources :movies, except: :new
  resources :lists

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :movies_lists
  has_many :movies, through: :movies_lists
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :movies_lists
  has_many :lists, through: :movies_lists

  validates :tmdb_id, uniqueness: true
end

app/models/movies_list.rb
class MoviesList < ApplicationRecord
  belongs_to :movie
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :list

  after_create :create_list

  delegate :movies, to: :list, allow_nil: true

  # def movies
  #   list.movies
  # end

  private

    def create_list
      List.find_or_create_by(user_id: id)
    end
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters,
    if: :devise_controller?
  before_action :set_queue, only:
    [:roulette, :queue, :remove_movie, :add_to_queue, :spin]
  before_action :set_movie, only: [:remove_movie, :details]
  before_action :set_list, only: [:details, :roulette, :add_to_queue]
  before_action :save, only: :details

  private

    def save
      details = Tmdb::Movie.detail(params[:tmdb_id])
      movie = Movie.new()

      movie.title = details.title
      movie.overview = details.overview
      movie.tagline = details.tagline
      movie.tmdb_id = details.id
      movie.homepage = details.homepage
      movie.adult = details.adult
      movie.runtime = details.runtime
      movie.imdb_id = details.imdb_id
      movie.poster_path = details.poster_path
      movie.popularity = details.popularity
      movie.save
      movie
    end

    def set_list
      @list = current_user.list.movies
    end

    def set_queue
      queue_ids = MoviesList.where(list_id: current_user.list.id).where(queue: true).pluck(:movie_id)
      @queue = Movie.find(queue_ids)
    end

    def set_movie
      this_movie_id = params[:id].nil? ? params[:tmdb_id] : params[:id]
      @movie = Movie.find_by(tmdb_id: this_movie_id)
    end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email])
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only:
    [:roulette, :destroy, :filter, :remove_movie]

  def roulette
  end

  def spin
    @winner = @queue.to_a.sample.title
  end

  def filter
  end

  def add_to_queue
    MoviesList.where(list_id: current_user.list.id).where(movie_id: params[:movie_id]).update(queue: true)

    set_queue
    set_list
    set_movie
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
  end

  def add
    if !Movie.find_by(tmdb_id: params[:tmdb_id])
      self.save
    end
    current_user.list.movies <<
                 Movie.find_by(tmdb_id: params[:tmdb_id])
    redirect_to details_path(tmdb_id: params[:tmdb_id])
  end

  def remove_from_list
    MoviesList.where(list_id: current_user.list.id).where(movie_id: params[:movie_id]).first.delete
    redirect_back fallback_location: :root
  end

  def remove_from_queue
    movie = MoviesList.where(list_id: current_user.list.id).where(movie_id: params[:movie_id]).first
    movie.update(queue: false)

    @movie = params[:movie_id]
    set_queue
    set_list
  end

  # def show
  #   @list = List.find(params[:list_id])
  # end

  private

    def list_params
      params.require(:list).permit(:name, :user_id)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def search
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  def details
    if (@movie = Movie.find_by(tmdb_id: params[:tmdb_id])).nil?
      @movie = Tmdb::Movie.detail(params[:tmdb_id])
      @not_saved = true
    else
      @movie = @movie.attributes
    end
  end

  def search_results
    @movies = Tmdb::Search.movie(params[:query], include_adult: params[:include_adult])
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:id, :imdb_id, :title, :overview, :poster_path, :runtime, :tagline, :tmdb_id, :homepage, :popularity, :vote_average, :adult)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/search_helper.rb
module SearchHelper
  def small_movie_poster_url(movie)
    # debugger
    CONFIG.images.secure_base_url +
    CONFIG.images.poster_sizes.first +
    if movie['poster_path']
      movie['poster_path']
    else
      movie.poster_path
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark fixed-top my-navbar">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li><%= link_to "Home", roulette_path, html: {id: "ajax_trigger"}, class: "btn btn-success mx-1" %></li>
      <li><%= link_to "Search", search_path, class: "btn btn-primary" %></li>
    </ul>
    <p class="notice"><%= notice %></p>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-warning mx-1" %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Roulette</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/navbar' %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<form>
  <div class="form-group">
    <label for="keywords">Keyword(s)</label>
    <input type="text" class="form-control" id="keywords">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/lists/_list.html.erb
<% if type == 'queue' %>
  <% if list.length > 0 %>
    <h2>Your Queue</h2>
  <% else %>
    <h2>No Queue Yet</h2>
  <% end %>
<% else %>
  <% if list.length == 0 %>
    <h5>There's nothing in your list yet.</h5><br>
    <%= link_to "Find Movies", search_path, class: "btn btn-primary m-3" %>
  <% else %>
    <h2>Your List</h2>
  <% end %>
<% end %>
<ul class="list-group">
  <% list.each do |movie| %>
    <li class="list-group-item p-1">
      <%= link_to details_path(tmdb_id: movie.tmdb_id) do %>
        <h6 class="my-0"><%= movie.title %></h6>
      <% end %>
      <% classes = "btn btn-sm btn-success mx-1" %>
      <% if type != 'queue' %>
        <% classes << " disabled" if @queue.to_a.pluck(:tmdb_id).include? movie.tmdb_id  %>
        <%= link_to 'Add to Queue', queue_path(movie_id: movie.id), method: :post, remote: true, class: classes %>
        <%= link_to 'Delete from List', remove_from_list_path(movie_id: movie.id), method: :post, remote: true, class: "btn btn-sm btn-danger" %>
      <% else %>
        <%= link_to 'Remove from Queue', remove_from_queue_path(movie_id: movie.id), method: :post,
        remote: true, class: "btn btn-sm btn-warning" %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/lists/_movie.html.erb
<% if !@movie['poster_path'].nil? %>
  <%= image_tag small_movie_poster_url(@movie) %>
<% end %>

app/views/lists/add_to_queue.js.erb
$('#queue').html("<%= j (render 'list', list: @queue, type: 'queue') %>");
$('#list').html("<%= j (render 'list', list: @list, type: 'list') %>");

app/views/lists/filter.js.erb
$('#filter-form').html("<%= j (render 'form', list: @list) %>");
$('#filter-form').slideDown(350);

app/views/lists/remove_from_queue.js.erb
$('#queue').html("<%= j (render 'list', list: @queue, type: 'queue') %>");
$('#list').html("<%= j (render 'list', list: @list, type: 'list') %>");

app/views/lists/remove_movie.js.erb
$('#queue').html("<%= j (render 'list', list: @queue, type: 'queue') %>");
$('#list').html("<%= j (render 'list', list: @list, type: 'list') %>");

app/views/lists/roulette.html.erb
<div class="container">
  <div class="row">
    <div class="section">
      <%= link_to filter_path, remote: true do %>
        <button class="btn btn-default"><span class="fa fa-plus"></span> Filter List</button>
      <% end %>
      <div id="filter-form" style="display:none;"></div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="card my-4">
        <div id="list"><%= render partial: 'list', locals: { list: @list, type: 'list'} %></div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card my-4">
        <div id="queue" class="queue"><%= render partial: 'list', locals: { list: @queue, type: 'queue' } %></div>
        <%= link_to 'Spin The Wheel!', spin_path, remote:true, html: {id: "ajax_trigger"}, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
    </div>
  </div>
</div>


<h1 id="winner"></h1>

<script type="text/javascript">
  function loadList(){
    $getJSON("/list.json", function(data){
      var html = "";
      $.each(data, function(index){
        alert(data[index].content);
        html += ""
      })
    })
  }
</script>

app/views/lists/spin.js.erb
$('#winner').html('...and the winner is...<br><%= j (@winner) %>!');

app/views/movies/_form.html.erb
<%= form_with url: '/search_results', method: :get, local: true do |form| %>

  <div class="form-group">
    <%= form.label :query %><br>
    <%= form.text_field :query %>
  </div>

  <div class="form-group">
    <%#= form.label :adult %>
    <%#= form.check_box :include_adult, {}, true, false %>
  </div>

  <div class="actions">
    <%= form.submit "Search", name: nil %>
  </div>
<% end %>

app/views/movies/_list_button.html.erb
<% if list.to_a.pluck(:tmdb_id).include? movie['tmdb_id'] %>
  <%= link_to 'Remove from List', remove_from_list_path(movie_id: movie['id'], tmdb_id: movie['tmdb_id']), id: "remove-from-list-button", method: :post, remote: true, class: "btn btn-sm btn-primary" %>
<% else %>
  <%= link_to 'Add to List', add_path(tmdb_id: movie['tmdb_id']), id: "add-to-list-button", method: :post, remote: true, class: "btn btn-sm btn-primary" %>
<% end %>

app/views/movies/details.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm word-wrap">
      <% if !@movie['poster_path'].nil? %>
        <%= image_tag small_movie_poster_url(@movie) %>
      <% end %>
      <h2><%= @movie['title'] %></h2>
      <span id="queue-button"><%= render 'list_button', list: @list, movie: @movie %></span>
      <div class="list-group">
        <p>
            <% @movie.each_pair do |key, value| %>
              <p class="list-group-item">
                <strong><%= key %>: </strong><%= value %>
            <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/movies/search.html.erb
<h1>
  Search for a Movie
</h1>
<%= render 'form' %>

app/views/movies/search_results.html.erb
<div class="container">
  <div class="row">
    <% if @movies.nil? %>
      <h3>No movies found.</h3>
    <% else %>
      <ul class="media-list">
        <% @movies.results.each do |movie| %>
          <li class="media">
            <div class="media-left">
              <% if !movie.poster_path.nil? %>
                <%= image_tag small_movie_poster_url(movie) %>
              <% end %>
            </div>
            <div class="media-body">
              <h4 class="media-heading">
                <%= link_to movie.title, details_path(tmdb_id: movie.id) %>
                <% if movie.adult == true %>
                  <div class='badge badge-info'>Adult</div>
                <% end %>
              </h4>
              <ul>
                <li><strong>tmdb_id </strong><%= movie.id %></li>
                <li><strong>movie.release_date </strong><%= movie.release_date %></li>
                <li><strong>movie.overview </strong><%= movie.overview %></li>
                <li><strong>adult </strong><%= movie.adult %></li>
              </ul>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>